/**
 * brand add-model — install a 3D model and its switchable channels into
 * `logos/<slug>/model/`, with the gates that make the result trustworthy.
 *
 * Step 2 of docs/model-channels-spec.md. This is the ONLY safe door into the
 * model role: it is where the checks that cannot run later run once.
 *
 *   brand add-model <slug> --from <dir> [--dry-run] [--yes]
 *                          [--logos <path>] [--manifest <path>] [--json]
 *
 * The gates, and why each one is a refusal rather than a warning:
 *
 *   GATE-SEQUENCE — refuses when the existing manifest records anything under
 *     `<slug>/model/` with a role this build would not assign. That is the
 *     signature of a manifest generated by a build predating MODEL_DIR, which
 *     silently filed model files as `role: "gallery"`. Such a manifest is
 *     structurally valid and verifies clean, so nothing about it looks broken
 *     — the check has to be explicit or the wrongness is invisible.
 *
 *   NESTED LAYOUT — refuses on any subdirectory inside the source. The
 *     manifest's scan is two-level bounded, so a nested file would be copied
 *     in and then never hashed: present on disk, absent from the manifest,
 *     invisible to `brand verify`. The walker cannot warn about what it does
 *     not look at, so the refusal belongs here, at the door.
 *
 *   CHECK-CAT — for every channel declaring `categorical: true`, proves the
 *     image cannot contain a colour outside the declared palette (see
 *     png-palette.ts for why an indexed PNG makes this a proof rather than a
 *     sample). This is the FIRST LEG of the conformance induction: check once
 *     at ingest, then `brand verify` proves the bytes have not changed since.
 *     If it does not run here it cannot be reconstructed later.
 *
 * The budget is deliberately NOT a gate. It is reported. A byte overage is a
 * result to escalate, not a licence to reach for lossy compression on a
 * categorical channel — and promoting a diagnostic to a halt is a mistake this
 * design has already recorded once.
 *
 * Scratch directories reuse add-gallery's `stagingDirFor`/`backupDirFor`
 * (`.brand-staging-*` / `.brand-backup-*`) rather than inventing a new prefix.
 * remove.ts records the reason and it applies unchanged here: a new prefix
 * would NOT be covered by manifest.ts's GALLERY_SCRATCH_DIR_PATTERNS denylist,
 * so the manifest could hash transient files. Reusing the existing names gets
 * both of manifest.ts's defences for free, today, with no cross-domain change.
 *
 * Exit codes (same contract as the rest of the CLI):
 *   0 — installed successfully, or a dry-run preview
 *   1 — refused (missing --yes on a real run) — "look again", not broken
 *   2 — operator error (bad slug, missing dir, unreadable/invalid view.json,
 *       nested layout, a failed gate)
 *   3 — unexpected error (IO failure, manifest regeneration failure)
 */

import chalk from 'chalk';
import {
  existsSync,
  readdirSync,
  readFileSync,
  statSync,
  mkdirSync,
  copyFileSync,
  renameSync,
  rmSync,
} from 'node:fs';
import { join, extname } from 'node:path';
import {
  generateManifest,
  writeManifest,
  readManifest,
  findMisroledModelAssets,
  MODEL_DIR,
} from '../manifest.js';
import { validateSlug, stagingDirFor, backupDirFor } from './add-gallery.js';
import { parseModelView, type ModelView } from '../model-view.js';
import { checkCategoricalPalette, PngParseError } from '../png-palette.js';

export interface AddModelOptions {
  slug: string;
  from: string;
  logos: string;
  manifest: string;
  dryRun?: boolean;
  yes?: boolean;
  json?: boolean;
  quiet?: boolean;
}

class AddModelError extends Error {
  readonly exitCode: number;
  readonly code: string;
  constructor(message: string, exitCode: number, code: string) {
    super(message);
    this.name = 'AddModelError';
    this.exitCode = exitCode;
    this.code = code;
  }
}

function refuse(message: string, exitCode: number, code: string): never {
  throw new AddModelError(message, exitCode, code);
}

/** Extensions the manifest's model scan tracks. Anything else is reported, never copied silently. */
const TRACKED_MODEL_EXTS = new Set(['.glb', '.png', '.webp', '.json']);

interface PlannedFile {
  name: string;
  bytes: number;
}

interface AddModelPlan {
  view: ModelView;
  files: PlannedFile[];
  untracked: string[];
  budgetNotes: string[];
  categorical: Array<{ id: string; texture: string; paletteSize: number; unused: string[] }>;
  replacing: boolean;
}

/**
 * Build the full plan and run every gate. Performs no writes — a dry run and a
 * real run share this exactly, so a preview can never diverge from what the
 * real run would do.
 */
function planAddModel(opts: AddModelOptions): AddModelPlan {
  const sourceDir = opts.from;
  if (!existsSync(sourceDir) || !statSync(sourceDir).isDirectory()) {
    refuse(`--from directory not found: ${sourceDir}`, 2, 'source-not-found');
  }
  const slugDir = join(opts.logos, opts.slug);
  if (!existsSync(slugDir)) {
    refuse(
      `slug "${opts.slug}" not found under ${opts.logos}. Add its primary logo first.`,
      2,
      'slug-not-found'
    );
  }

  // GATE-SEQUENCE, before anything is read from the source: if the manifest on
  // disk predates the model role, installing into it would produce a tree the
  // manifest describes wrongly.
  if (existsSync(opts.manifest)) {
    let misroled: string[] = [];
    try {
      misroled = findMisroledModelAssets(readManifest(opts.manifest));
    } catch (err) {
      refuse(`Could not read ${opts.manifest}: ${(err as Error).message}`, 2, 'manifest-unreadable');
    }
    if (misroled.length > 0) {
      refuse(
        `GATE-SEQUENCE: ${misroled.length} asset(s) under model/ carry a role this build would ` +
          `not assign — the manifest was generated before the model role existed and files them ` +
          `as gallery images:\n` +
          misroled.map(k => `    ${k}`).join('\n') +
          `\n  Fix: run \`brand manifest\` to regenerate, then re-run this command.`,
        2,
        'gate-sequence'
      );
    }
  }

  // NESTED LAYOUT — refuse loudly. The manifest's model scan is two-level
  // bounded, so anything in a subdirectory would be copied and never hashed.
  const entries = readdirSync(sourceDir, { withFileTypes: true });
  const dirs = entries.filter(e => e.isDirectory()).map(e => e.name);
  if (dirs.length > 0) {
    refuse(
      `Nested directories are not supported in a model source: ${dirs.join(', ')}.\n` +
        `  The manifest scans model/ exactly one level deep, so a nested file would be copied ` +
        `in and never hashed — present on disk, absent from the manifest, invisible to ` +
        `\`brand verify\`.\n  Fix: flatten the layout (channels are ch_<id>.<ext> beside ` +
        `asset.glb and view.json).`,
      2,
      'nested-layout'
    );
  }

  const fileNames = entries.filter(e => e.isFile()).map(e => e.name);

  // view.json is mandatory: without it there is no channel list, and brand has
  // no way to invent one — the semantics are the subject's to supply.
  if (!fileNames.includes('view.json')) {
    refuse(`No view.json in ${sourceDir}. It describes the channels; brand cannot infer them.`, 2, 'no-view-json');
  }
  let view: ModelView;
  try {
    view = parseModelView(readFileSync(join(sourceDir, 'view.json'), 'utf-8'), join(sourceDir, 'view.json'));
  } catch (err) {
    refuse((err as Error).message, 2, 'invalid-view-json');
  }

  // Every file view.json references must actually be here.
  const missing: string[] = [];
  if (!fileNames.includes(view.asset)) missing.push(view.asset);
  for (const ch of view.channels) {
    if (!fileNames.includes(ch.texture)) missing.push(ch.texture);
  }
  if (missing.length > 0) {
    refuse(
      `view.json references ${missing.length} file(s) missing from ${sourceDir}: ${missing.join(', ')}`,
      2,
      'missing-referenced-file'
    );
  }

  // CHECK-CAT — the first leg of the conformance induction.
  const categorical: AddModelPlan['categorical'] = [];
  for (const ch of view.channels) {
    if (!ch.categorical) continue;
    const texPath = join(sourceDir, ch.texture);
    // parseModelView already guarantees a non-empty palette for a categorical
    // channel, so `ch.palette!` is safe here.
    try {
      const result = checkCategoricalPalette(readFileSync(texPath), ch.palette!, texPath);
      if (!result.ok) {
        refuse(
          `CHECK-CAT failed for channel "${ch.id}" (${ch.texture}): ${result.undeclared.length} ` +
            `colour(s) present in the image are not declared in its palette: ` +
            `${result.undeclared.join(', ')}.\n` +
            `  A colour outside the declared set is a class no measurement produced.`,
          2,
          'check-cat'
        );
      }
      categorical.push({
        id: ch.id,
        texture: ch.texture,
        paletteSize: result.paletteSize,
        unused: result.unused,
      });
    } catch (err) {
      if (err instanceof PngParseError) {
        refuse(`CHECK-CAT could not verify channel "${ch.id}" (${ch.texture}): ${err.message}`, 2, 'check-cat');
      }
      throw err;
    }
  }

  // Everything else in the directory: tracked files get copied, untracked ones
  // are REPORTED rather than silently skipped or silently copied.
  const files: PlannedFile[] = [];
  const untracked: string[] = [];
  for (const name of fileNames.sort()) {
    if (!TRACKED_MODEL_EXTS.has(extname(name).toLowerCase())) {
      untracked.push(name);
      continue;
    }
    files.push({ name, bytes: statSync(join(sourceDir, name)).size });
  }

  // Budget: reported, never a gate.
  const budgetNotes: string[] = [];
  const budget = view.budget;
  if (budget) {
    const assetFile = files.find(f => f.name === view.asset);
    if (budget.asset_bytes && assetFile && assetFile.bytes > budget.asset_bytes) {
      budgetNotes.push(
        `${view.asset} is ${assetFile.bytes.toLocaleString()} bytes, over its declared ` +
          `${budget.asset_bytes.toLocaleString()} budget.`
      );
    }
    if (budget.channel_bytes) {
      for (const ch of view.channels) {
        const f = files.find(x => x.name === ch.texture);
        if (f && f.bytes > budget.channel_bytes) {
          budgetNotes.push(
            `${ch.texture} is ${f.bytes.toLocaleString()} bytes, over the declared ` +
              `${budget.channel_bytes.toLocaleString()} per-channel budget.`
          );
        }
      }
    }
  }

  return {
    view,
    files,
    untracked,
    budgetNotes,
    categorical,
    replacing: existsSync(join(slugDir, MODEL_DIR)),
  };
}

export async function runAddModel(opts: AddModelOptions): Promise<void> {
  try {
    validateSlug(opts.slug);
  } catch (err) {
    return emitError((err as Error).message, 2, 'invalid-slug', opts);
  }

  let plan: AddModelPlan;
  try {
    plan = planAddModel(opts);
  } catch (err) {
    if (err instanceof AddModelError) return emitError(err.message, err.exitCode, err.code, opts);
    return emitError(`Unexpected error: ${(err as Error).message}`, 3, 'unexpected', opts);
  }

  const totalBytes = plan.files.reduce((n, f) => n + f.bytes, 0);

  if (opts.dryRun) {
    return emitOk(plan, totalBytes, opts, true);
  }
  if (!opts.yes) {
    return emitError(
      `Refusing to ${plan.replacing ? 'REPLACE the existing' : 'install a'} model/ for "${opts.slug}" ` +
        `without --yes (${plan.files.length} files, ${totalBytes.toLocaleString()} bytes).\n` +
        `  Re-run: brand add-model ${opts.slug} --from ${opts.from} --yes`,
      1,
      'needs-confirmation',
      opts
    );
  }

  // Swap-based install, same spirit as add-gallery/remove: build the new tree
  // in a reserved sibling, move any existing tree aside (never delete it
  // outright), swap the new one in, regenerate the manifest, and only then
  // discard the backup. If manifest regeneration throws, the swap is reversed
  // so the operator never sees a half-installed tree beside a stale manifest.
  const targetDir = join(opts.logos, opts.slug, MODEL_DIR);
  const stagingDir = stagingDirFor(targetDir);
  const backupDir = backupDirFor(targetDir);
  let movedAside = false;

  try {
    mkdirSync(stagingDir, { recursive: true });
    for (const f of plan.files) {
      copyFileSync(join(opts.from, f.name), join(stagingDir, f.name));
    }
    if (plan.replacing) {
      renameSync(targetDir, backupDir);
      movedAside = true;
    }
    renameSync(stagingDir, targetDir);

    writeManifest(generateManifest(opts.logos), opts.manifest);

    if (movedAside) rmSync(backupDir, { recursive: true, force: true });
  } catch (err) {
    // Reverse in the opposite order to the swap.
    try {
      if (existsSync(targetDir) && movedAside) rmSync(targetDir, { recursive: true, force: true });
      if (movedAside && existsSync(backupDir)) renameSync(backupDir, targetDir);
      if (existsSync(stagingDir)) rmSync(stagingDir, { recursive: true, force: true });
    } catch (restoreErr) {
      // Report the truth when the restore also fails (remove.ts, 337be64).
      return emitError(
        `Install failed: ${(err as Error).message}\n` +
          `  AND the rollback also failed: ${(restoreErr as Error).message}\n` +
          `  The tree may be inconsistent. Inspect ${targetDir}, ${stagingDir} and ${backupDir}.`,
        3,
        'install-and-rollback-failed',
        opts
      );
    }
    return emitError(`Install failed and was rolled back: ${(err as Error).message}`, 3, 'install-failed', opts);
  }

  return emitOk(plan, totalBytes, opts, false);
}

function emitOk(plan: AddModelPlan, totalBytes: number, opts: AddModelOptions, dryRun: boolean): void {
  if (opts.json) {
    console.log(
      JSON.stringify(
        {
          ok: true,
          dryRun,
          slug: opts.slug,
          replacing: plan.replacing,
          asset: plan.view.asset,
          channels: plan.view.channels.map(c => ({ id: c.id, categorical: c.categorical })),
          files: plan.files,
          totalBytes,
          untracked: plan.untracked,
          budgetNotes: plan.budgetNotes,
          categorical: plan.categorical,
        },
        null,
        2
      )
    );
    return;
  }
  if (opts.quiet) return;

  const verb = dryRun ? 'Would install' : plan.replacing ? 'Replaced' : 'Installed';
  console.log(chalk.bold(`\n  ${verb} model/ for ${opts.slug}`));
  console.log('');
  console.log(`  Asset:     ${chalk.cyan(plan.view.asset)}`);
  console.log(`  Channels:  ${chalk.cyan(String(plan.view.channels.length))}`);
  for (const ch of plan.view.channels) {
    const cat = plan.categorical.find(c => c.id === ch.id);
    const tag = cat ? chalk.dim(` [categorical, ${cat.paletteSize} colours verified]`) : '';
    console.log(`    ${ch.id.padEnd(14)} ${chalk.dim(ch.texture)}${tag}`);
  }
  console.log(`  Files:     ${chalk.cyan(String(plan.files.length))} (${totalBytes.toLocaleString()} bytes)`);

  for (const c of plan.categorical) {
    if (c.unused.length > 0) {
      console.log(
        chalk.dim(`  note: channel "${c.id}" declares ${c.unused.length} palette colour(s) it never uses.`)
      );
    }
  }
  if (plan.untracked.length > 0) {
    console.log(chalk.yellow(`  skipped (untracked extension): ${plan.untracked.join(', ')}`));
  }
  for (const note of plan.budgetNotes) {
    // Reported, not a gate — see this file's header.
    console.log(chalk.yellow(`  budget: ${note}`));
  }
  if (dryRun) {
    console.log(chalk.dim('\n  Dry run — nothing was written.'));
  }
  console.log('');
}

function emitError(message: string, exitCode: number, code: string, opts: AddModelOptions): void {
  if (opts.json) {
    console.log(JSON.stringify({ ok: false, error: code, slug: opts.slug, message }, null, 2));
  } else {
    console.error(chalk.red(`\n  ✗ ${message}\n`));
  }
  process.exitCode = exitCode;
}
